# Generated by Django 4.1.4 on 2022-12-29 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('grape', models.CharField(max_length=50)),
                ('vintage', models.IntegerField()),
                ('fortified', models.BooleanField()),
                ('sparkling', models.BooleanField()),
                ('desert', models.BooleanField()),
                ('color', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Horrible'), (2, 'Not for me'), (3, 'It was wine'), (4, 'I liked it'), (5, 'Loved it, new favorite')])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tastings.event')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tastings.wine')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='wines',
            field=models.ManyToManyField(to='tastings.wine'),
        ),
    ]
