# Generated by Django 4.1.4 on 2022-12-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='producer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.IntegerField(null=True),
        ),
    ]
