# Generated by Django 4.1.4 on 2022-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastings', '0002_alter_wine_brand_alter_wine_country_alter_wine_grape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
