# Generated by Django 4.1.4 on 2022-12-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastings', '0003_alter_wine_brand_alter_wine_country_alter_wine_grape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='thoughts',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
