# Generated by Django 4.1.4 on 2023-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSurveyResponse',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('meeting_preference', models.IntegerField(choices=[(0, 'Weekly'), (1, 'Biweekly'), (2, 'Monthly')])),
                ('oneglassorseveral', models.IntegerField(choices=[(0, 'One glass'), (1, 'Several')])),
                ('pay', models.IntegerField(choices=[(0, '$0'), (1, '$1-$5'), (2, '$6-$10')])),
            ],
        ),
    ]
