# Generated by Django 4.1.4 on 2023-01-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_initialsurveyresponse_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialsurveyresponse',
            name='pay',
            field=models.IntegerField(choices=[(0, '$0'), (1, '$1-$5'), (2, '$6-$10')], verbose_name="How much would you be willing to pay to attend? (We don't have funding due to the illegal nature of the club, but the price will likely be very low! $1-5 range)"),
        ),
    ]
