# Generated by Django 4.1.4 on 2023-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_initialsurveyresponse_favoritewine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialsurveyresponse',
            name='favoritewine',
            field=models.CharField(blank=True, max_length=200, verbose_name='Favorite wine?'),
        ),
    ]
